[workspace]
members = [
  "delegation-manager/program",
  "delegation-manager/examples/counter_example",
  "delegation-manager/examples/civic_example"
]

[features]
seeds = false
skip-lint = false

[programs.localnet]
delegation_manager = "6rBfJockUbwDjpJaa755PwdtNNGY5ZubVk9QgjuqDUDG"
counter_example = "GUQeLoyQs7YjPrK2gzbJ3QWrGygR4bKmpwSQ2eMv6cYj"
civic_example = "9XMVrhZ7r6MxZ6fgHBL8rWbpRTAxtoK4EhvGBmjqj9ux"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "wallets/unique-test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 100000