[workspace]
members = [
  "delegation-manager/program",
  "delegation-manager/example"
]

[features]
seeds = false
skip-lint = false

[programs.localnet]
delegation_manager = "FG82Bh2yS5dcydGXk2PCkZb3sEZdcDTXPJhQQ83kDK1n"
example = "972QDtrTG4KvzEVt6fvxNmXQpuRyFhnpcR4Ln9Y41w5a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "wallets/unique-test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
