[features]
seeds = false
skip-lint = false
[programs.localnet]
delegate_manager = "3Q8TuzBaXYjJtKyxAgZwr3ehkUWh2sBAwmwyjjJYHePK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "wallets/unique-test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
