[workspace]
members = [
  "delegation-manager/program",
  "delegation-manager/example",
  "delegation-manager/program-vanila"
]

[features]
seeds = false
skip-lint = false

[programs.localnet]
delegation_manager = "5mcBrxdfAZZkBfThVY6HwkmZSbAhDNhNdxUiHqyhqZCA"
example = "972QDtrTG4KvzEVt6fvxNmXQpuRyFhnpcR4Ln9Y41w5a"
delegation_manager_vanila = "BVZtShyAQsxhy1uQqYFemi8NHdN8QThr8Mv5RjbW8vvQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "wallets/unique-test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
